version: 2.1

jobs:
  commitlint:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Fetch commit message
          command: echo "$(git log -1 --pretty=%B)" > commit-msg.txt
      - run:
          name: Validate commit message
          command: npx commitlint --from=HEAD~1 --to=HEAD

workflows:
  version: 2
  test:
    jobs:
      - commitlint
