version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17  # Use CircleCI's Node.js image

jobs:
  commitlint:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install specific npm version
          command: sudo npm install -g npm@10.8.3  # Use sudo
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Fetch commit message
          command: echo "$(git log -1 --pretty=%B)" > commit-msg.txt
      - run:
          name: Validate commit message
          command: npx commitlint --from=HEAD~1 --to=HEAD
      - run:
          name: Run ESLint
          command: npm run lint

workflows:
  version: 2
  test:
    jobs:
      - commitlint
